CREATE TABLE IF NOT EXISTS users(
    USER_ID INTEGER PRIMARY KEY,
    LOGIN VARCHAR(32) NOT NULL,
    PASSWORD VARCHAR(32) NOT NULL,
    KEY VARCHAR(32) NOT NULL
);

CREATE TABLE IF NOT EXISTS chats(
    CHAT_ID INTEGER PRIMARY KEY,
    USER1 INTEGER NOT NULL,
    USER2 INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS messages(
    MESSAGE_ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    MESSAGE TEXT NOT NULL,
    TIME INTEGER NOT NULL,
    CHAT_ID INTEGER NOT NULL
);